-- 코드를 입력하세요
SELECT DATE_FORMAT(B.SALES_DATE, '%Y')YEAR, 
MONTH(B.SALES_DATE)MONTH, 
COUNT(DISTINCT B.USER_ID)PUCHASED_USERS, 
ROUND(COUNT(DISTINCT B.USER_ID)/(SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'), 1)PUCHASED_RATIO

FROM ONLINE_SALE AS B
JOIN USER_INFO AS A
ON A.USER_ID = B.USER_ID 
AND A.JOINED BETWEEN '2021-01-01' AND '2021-12-31'

GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;
